{
     "language-command-description-activate-containers-for-workflow": "Aktiverer eventuelle workflow container views som er assosiert med en gitt workflow.",
     "language-command-description-activate-view": "Aktiverer et view.",
     "language-command-description-add-markup": "Legger gitt geometri til påtegningslaget.",
     "language-command-description-add-status": "Legger til en statusindikator på skjermen.",
     "language-command-description-add-temporary-markup-geometry": "Legger til midlertidig påtegning i kartet. Kommandoen ClearTemporaryMarkup fjerner påtegningen.",
     "language-command-description-add-text-markup": "Ber brukeren om tekst som skal legges til i kartet som påtegning. Når brukeren er ferdig legges teksten til på den gitte geometrien.",
     "language-command-description-alert": "Viser en advarsel.",
     "language-command-description-allow-hide-feature-layer-modal-message": "Viser Lukkeknappen på ModalMessageView og gir brukeren mulighet til å lukke beskjeden.",
     "language-command-description-cancel-search": "Avbryt søk hos alle tilbydere.",
     "language-command-description-change-edit-log-entry": "Endre en eksisterende oppføring i redigeringsloggen.",
     "language-command-description-clear-active-tool": "Nullstiller det aktive verktøyet.",
     "language-command-description-clear-default-highlights": "Fjerner utheving fra det vanlige uthevingslaget.",
     "language-command-description-clear-highlights": "Fjerner utheving fra det aktive uthevingslaget.",
     "language-command-description-clear-markup": "Ber brukeren om bekreftelse, og fjerner all utheving fra uthevingslaget hvis brukeren sier ja.",
     "language-command-description-clear-markup-quiet": "Tømmer all utheving fra uthevingslaget uten å be om bekreftelse.",
     "language-command-description-clear-storage-for-application": "Tømmer offlinedata for den aktive applikasjonen.",
     "language-command-description-clear-storage-for-domain": "Tømmer all offlinedata for det aktive domenet. Dette inkluderer data for alle applikasjoner lastet fra det aktive domenet.",
     "language-command-description-clear-temporary-markup": "Fjerner midlertidig utheving som er laget med AddTemporaryMarkupGeometry.",
     "language-command-description-close-data-frame": "Lukker DataRegion, hvis den er tilgjengelig i det aktive skallet (shell).",
     "language-command-description-close-feature-set-collection": "Lukker feature set-samlingen.",
     "language-command-description-close-modal-region": "Lukker ModalWindowRegion.",
     "language-command-description-close-results-frame": "Deaktiverer ResultsRegion.",
     "language-command-description-confirm": "Viser en bekreftelsesmelding.",
     "language-command-description-create-attachment": "Lager et vedlegg til et objekt.",
     "language-command-description-create-feature": "Lager et nytt objekt.",
     "language-command-description-create-highlight-layer": "Lager et nytt uthevingslag med navnet brukeren oppgir.",
     "language-command-description-create-related-record": "Lager en oppføring i en relatert tabell.",
     "language-command-description-deactivate-containers-for-workflow": "Deaktiverer alle workflow views som er assosiert med en gitt workflow.",
     "language-command-description-deactivate-view": "Deaktiverer et view.",
     "language-command-description-delete-attachment": "Sletter vedlegget til et objekt.",
     "language-command-description-delete-feature": "Sletter et nytt eller eksisterende objekt.",
     "language-command-description-delete-from-edit-log": "Fjerner den gitte oppføringen fra redigeringsloggen, og setter så redigeringsloggen.",
     "language-command-description-delete-related-record": "Sletter oppføring i en relatert tabell.",
     "language-command-description-destroy-view": "Ødelegger et view, dvs. tømmer viewet sine bindinger og DOM-substrukturer..",
     "language-command-description-display-workflow-container-content": "Viser et view i en workflow container.",
     "language-command-description-feature-layer-cache-data": "Cacher dataene for en gitt karttjeneste-URL.",
     "language-command-description-feature-layer-clear-cache-spec": "Gi beskjed om at dette laget ikke skal caches ved neste synkronisering.",
     "language-command-description-feature-layer-clear-data": "Tømmer data for en gitt karttjeneste-URL.",
     "language-command-description-feature-layer-module-refresh-data": "Oppdaterer sammendrag for lagredigeringer og \"sync needed\"-flagget (synkronisering trengs-flagget).",
     "language-command-description-feature-layer-module-start-sync": "Begynner å synkronisere endringer i objekter til serveren.",
     "language-command-description-fsm-collection-set-command": "Gjør at den valgte kommandoen åpner feature set-samlingen for det gitte kildenavnet.",
     "language-command-description-geolocate": "Zoomer til der enheten er.",
     "language-command-description-get-edit-log": "Henter redigeringsloggen og sender den til et callback. Hvis en feil oppstår sendes feilen til callback-en.",
     "language-command-description-get-feature-details-providers": "Oppretter view for alle konfigurerte objektdetaljtilbydere og bygger dem inn i objektdetaljdialogen.",
     "language-command-description-get-related-feature": "Henter objekter som er relatert til objektet.",
     "language-command-description-global-search": "Utfører et søk hos alle aktive tilbydere.",
     "language-command-description-hide-feature-layer-modal-message": "Fjerner en modal message.",
     "language-command-description-hide-map-element": "Fjerner element som tidligere har blitt festet til kartet med ShowMapElement.",
     "language-command-description-highlight-esri-feature-set": "Uthever alle objektene i det gitte feature settet i det aktive uthevingslaget.",
     "language-command-description-highlight-feature": "Uthever objektet i det aktive uthevingslaget.",
     "language-command-description-highlight-feature-default": "Uthever objektet i standardlaget for utheving.",
     "language-command-description-highlight-feature-set": "Uthever alle objektene i det gitte feature settet i det aktive uthevingslaget.",
     "language-command-description-identify": "Viser informasjon fra en geometri.",
     "language-command-description-initialize-site": "Gir beskjed til Geocortex Essentials Site-objektet om å starte initialisering.",
     "language-command-description-invoke-map-tip": "Viser informasjon på den gitte geomtrien og bruker Karttips (\"MapTip\") som kilde.",
     "language-command-description-map-resize": "Ber kartet om å gjenopprette seg til opprinnelig størrelse. Denne bør kalles etter å ha endret størrelsen til en kartbeholder (map container).",
     "language-command-description-open-data-frame": "Åpner DataRegion, hvis den er tilgjengelig i aktivt skall (shell).",
     "language-command-description-open-feature-set-collection": "Åpner feature set-samlingen.",
     "language-command-description-open-results-frame": "Aktiverer ResultsRegion.",
     "language-command-description-open-web-page": "Åpner en nettside i en annen fane/vindu.",
     "language-command-description-pan-to-feature": "Panorerer til Geocortex-objektet.",
     "language-command-description-pan-to-point": "Panorerer til et punkt eller en annen type geometri.",
     "language-command-description-project": "Kaller en geomtritjeneste for å projisere geometrier mellom ulike koordinatsystemer.",
     "language-command-description-prompt": "Viser en melding som krever svar fra brukeren.",
     "language-command-description-pulse-status": "Nullstiller tidtakeren for statusen til viewModel.",
     "language-command-description-recenter-map-on-next-map-resize": "Sentrerer kartet til eksisterende plassering neste gang størrelsen til kartet endres.",
     "language-command-description-register-search-provider": "Registrerer en søketilbyder hvis den ikke allerede er registrert.",
     "language-command-description-remove-feature-set-collection": "Fjerner valgt samling fra feature set-behandleren.",
     "language-command-description-remove-feature-set-collection-by-id": "Fjerner valgt samling fra feature set-behandleren.",
     "language-command-description-remove-highlight-layer": "Fjerner uthevingslaget med valgt navn, hvis det finnes.",
     "language-command-description-remove-status": "Removes the status indicator from the screen with the specified ID.",
     "language-command-description-run-workflow-by-id": "Runs a workflow.",
     "language-command-description-run-workflow-with-arguments": "Runs a workflow with a set of input arguments.",
     "language-command-description-run-workflow-with-geometry": "Runs a workflow with a geometry used as an input argument.",
     "language-command-description-search": "Performs a search on all active providers.",
     "language-command-description-set-active-highlight-layer": "Sets the layer with the specified name as active, if there is one.",
     "language-command-description-set-active-tool": "Sets the active tool.",
     "language-command-description-set-edit-log": "Sets the edit log, passing it into a callback. If an error occurs, the error is passed into the callback.",
     "language-command-description-set-editor-feature-geometry": "Sets the geometry of the feature that is currently being edited in the Attribute Editor, and activates the AttributeEditor View.",
     "language-command-description-set-highlight-border-color": "Sets the border color used for new highlights, specified in 6 or 8 digit hex in RGB or ARGB form.",
     "language-command-description-set-highlight-fill-color": "Sets the fill color used for new highlights, specified in 6 or 8 digit hex in RGB or ARGB form.",
     "language-command-description-show-feature-details": "Creates and displays the Feature Details dialog for the feature or feature set collection specified.",
     "language-command-description-show-feature-layer-modal-message": "Creates a ModelMessageView view and displays the given message.",
     "language-command-description-show-feature-template-picker": "Shows the feature template picker used to create new features. If a layer is supplied, shows the templates for the layer.",
     "language-command-description-show-layer-list": "Activates the LayerList View.",
     "language-command-description-show-map": "Activates map view.",
     "language-command-description-show-map-callout": "Displays a map callout anchored to a given point.",
     "language-command-description-show-map-element": "Displays an element anchored to a specific point on the map.",
     "language-command-description-show-map-tip": "Creates a Map Tip View and displays the feature in it.",
     "language-command-description-show-map-tip-results": "Shows map tip results for a FeatureSetCollection previously added to the FeatureSetManager.",
     "language-command-description-show-results-feature-action": "Creates ResultsListFeatureActionsView and displays the Feature Actions.",
     "language-command-description-show-results-list": "Displays the list of features in the given feature set collection as a list.",
     "language-command-description-show-results-table": "Displays the list of features in the given feature set collection in a tabular view.",
     "language-command-description-start-editing-edit-log-entry": "Creates a aview to change an existing edit.",
     "language-command-description-start-editing-feature": "Begins editing an existing feature.",
     "language-command-description-start-editing-new-feature": "Begynner å redigere et nytt objekt.",
     "language-command-description-step-zoom-in": "Zoomer inn et hakk.",
     "language-command-description-step-zoom-out": "zoomer ut et hakk.",
     "language-command-description-take-application-offline": "Setter applikasjonen i offlinemodus.",
     "language-command-description-take-application-online": "Kobler applikasjonen til internett.",
     "language-command-description-toggle-data-frame": "Aktiverer eller deaktiverer dataområdet (data frame).",
     "language-command-description-toggle-log-view": "Aktiverer eller deaktiverer loggvisning.",
     "language-command-description-toggle-results-frame": "Aktiverer eller deaktiverer området som viser søkeresultater.",
     "language-command-description-toggle-view": "Aktiverer eller deaktiverer et view.",
     "language-command-description-update-attachment": "Oppdaterer vedlegget til et objekt.",
     "language-command-description-update-feature": "Oppdaterer et nytt eller eksisterende objekt.",
     "language-command-description-update-feature-layer-modal-message": "Oppdaterer den synlige ModelMessageView slik at den også tar med valgt melding.",
     "language-command-description-update-related-record": "Oppdaterer en oppføring i en relatert tabell.",
     "language-command-description-zoom-out-to-extent": "Zoomer ut til valgt utstrekning.",
     "language-command-description-zoom-to-esri-feature-set": "Zoomer til utstrekningen av alle objektene i feature settet.",
     "language-command-description-zoom-to-extent": "Zoomer til valgt utstrekning.",
     "language-command-description-zoom-to-feature": "Zoomer til et objekt.",
     "language-command-description-zoom-to-initial-extent": "Zoomer til åpningsutsrekningen til den aktive siten.",
     "language-common-back": "Tilbake",
     "language-common-cancel": "Avbryt",
     "language-common-clear": "Tøm",
     "language-common-close": "Lukk",
     "language-common-create": "Opprett",
	 "language-common-deactivate-tool": "Deaktiver verktøy",
     "language-common-debug-log-keys": "For å se loggen på en stasjonær PC, trykk Ctrl + Shift + ~. Trykk og hold verktøylinja på en mobil enhet.",
     "language-common-delete": "Slett",
     "language-common-done": "Ferdig",
     "language-common-edit": "Rediger",
     "language-common-editing": "Redigering",
     "language-common-extract-data": "Hent ut data",
     "language-common-feature-editing": "Objektegenskaper",
     "language-common-feature-editing-desc": "Rediger egenskapene til objektet og lagre.",
     "language-common-feature-editlog": "Se endringsloggen",
     "language-common-feature-editlog-desc": "Viser informasjon om redigeringshistorikken til redigeringslaget.",
     "language-common-feature-layer-details": "Synkroniseringsinnstillinger for {0}",
     "language-common-feature-layer-details-desc": "Behandle caching av et redigeringslag for offlinebruk.",
     "language-common-feature-offline-tools": "Behandle offlinedata.",
     "language-common-feature-sync-settings": "Behandle synkroniseringsinnstillinger",
     "language-common-feature-sync-settings-desc": "Viser en liste med redigeringslag å velge fra.",
     "language-common-feature-template-picker": "Lag et objekt",
     "language-common-feature-template-picker-desc": "Velg en objekttype.",
     "language-common-hide": "Skjul",
     "language-common-layer-data": "Kartlagsdata",
	 "language-common-load": "Last (load)",
     "language-common-loading": "Laster...",
     "language-common-login": "Logg inn",
     "language-common-no-results": "Ingen kartlag med informasjon her.",
     "language-common-no-results-desc": "Oppføringer vises etter at du gjør et søk med treff eller en annen handling som returnerer resultater.",
     "language-common-no-results-short": "Ingen resultater",
     "language-common-not-available-offline": "Du kan ikke gjøre sånn når du er offline.",
     "language-common-notification": "Informasjon",
     "language-common-ok": "OK",
     "language-common-pan": "Panorer",
     "language-common-pan-description": "Panorer kartet slik at dette objektet kommer midt i kartet.",
     "language-common-query-results": "Spørringsresultater",
	 "language-common-refresh": "Oppfrisk",
     "language-common-results": "Resultater",
	 "language-common-results-added-confirmation": "{0} resultat(er) er lagt til '{1}'",
     "language-common-results-intersect-confirmation": "'{0}' intersected with {1}",
     "language-common-results-removed-confirmation": "{0} resultat(er) er fjernet fra '{1}'",
     "language-common-results-replace-confirmation": "'{0}' erstattet med {1}",
     "language-common-results-subtract-confirmation": "{1} subtrahert/fjernet fra '{0}'",
     "language-common-results-union-confirmation": "'{0}' unioned with {1}",
     "language-common-save": "Lagre",
	 "language-common-saving": "Lagrer...",
	 "language-common-share": "Del",
     "language-common-show": "Vis",
     "language-common-show-details": "Se detaljer",
     "language-common-show-details-description": "Se flere detaljer for dette objektet.",
     "language-common-sync-complete": "Synkronisering er ferdig",
     "language-common-validation-symbol": "*",
     "language-common-view-log": "Se logg",
     "language-common-welcome": "Hjelp",
     "language-common-workflow": "Workflow",
     "language-content-policy-prompt-uri-accept-btn": "Ja",
     "language-content-policy-prompt-uri-desc": "Applikasjonen forsøker å laste innhold fra '{0}'. Vil du stole på denne URLen?",
     "language-content-policy-prompt-uri-reject-btn": "Nei, ikke last inn",
     "language-content-policy-prompt-uri-title": "Potensielt innhold fra ikke-godkjent kilde er funnet",
	 "language-coordinates-degrees": "°",
     "language-coordinates-east-abbrev": "O",
     "language-coordinates-latitude-abbrev": "Lat:",
     "language-coordinates-longitude-abbrev": "Lon:",
     "language-coordinates-minutes": "'",
     "language-coordinates-north-abbrev": "N",
     "language-coordinates-seconds": "\"",
     "language-coordinates-south-abbrev": "S",
     "language-coordinates-west-abbrev": "V",
     "language-coordinates-x": "X:",
     "language-coordinates-y": "Y:",
     "language-extract-data": "Hent ut data",
     "language-extract-data-description": "Hent ut objektdata fra kartet.",
     "language-framework-ui-view-container-view-back": "Gå tilbake {0}",
     "language-framework-ui-view-container-view-close": "Lukk {0}",
     "language-grant-editor-add-button-text": "Legg til",
     "language-grant-editor-add-button-title": "Legg til bruker eller gruppe",
     "language-grant-editor-global-grant-name-public": "Alle (Innlogging er ikke nødvendig)",
     "language-grant-editor-global-grant-name-user": "Alle (Innlogging er nødvendig)",
     "language-grant-editor-moniker-type-role": "Grupper",
     "language-grant-editor-moniker-type-user": "Individuelle",
     "language-grant-editor-remove-button-title": "Fjern brukeren eller gruppen",
     "language-grant-editor-search-placeholder": "Søk...",
     "language-grant-editor-search-title": "Skriv inn søkeordene",
     "language-grant-editor-table-header-edit": "Rediger",
     "language-grant-editor-table-header-none": "Ingen",
     "language-grant-editor-table-header-view": "Se",
     "language-layer-actions": "Utfører en handling på {0}",
     "language-layer-actions-desc": "Viser en liste med laghandlinger",
     "language-layer-actions-title": "Laghandlinger",
     "language-layer-actions-tooltip": "Klikk for å se hvilke handlinger som er tilgjengelig for {0} laget.",
     "language-layerlist-base-maps-folder-title": "Grunnlagskart",
     "language-layerlist-default-folder-title": "Kartlagsmappe",
     "language-layerlist-expand": "Kollaps eller ekspander {0} lag-gruppe",
     "language-layerlist-not-visible-at-extent": "Ikke synlig i den angitte målestokknivået.",
     "language-layerlist-operational-maps-folder-title": "Kartlag",
	 "language-layerlist-toggle": "Velg {0} kartlag synlighet.",
     "language-layerlist-user-added-layers-folder-title": "Brukerkartlag",
	 "language-layerlist-visible-at-extent": "Currently innenfor synlig målestokk.",
     "language-layerselector-icon-tooltip": "{0} icon",
     "language-layerselector-item-expand": "Minimer eller ekspander {0} laggruppen",
     "language-layerselector-state-toggle": "Velg {0} lag synlighet.",
     "language-menu-accessibility-panel": "Se tilretteleggingsfanen",
     "language-menu-accessibility-panel-desc": "Se informasjon om tilrettelegging av denne applikasjonen.",
     "language-menu-add-a-feature": "Lag et objekt",
     "language-menu-add-a-feature-desc": "Lag et nytt objekt i dette laget.",
     "language-menu-add-text": "Legg til tekst",
     "language-menu-add-text-desc": "Legg til tekst i kartet.",
     "language-menu-bookmark-add": "Legg til bokmerke av kartutsnittet",
     "language-menu-bookmark-add-desc": "Legg nåværende kartutsnitt til listen med bokmerker, så jeg kan gå til den senere.",
     "language-menu-browse-saved-results": "Åpne lagrede resultater",
     "language-menu-browse-saved-results-desc": "Velg fra listen med lagrede resultater for å åpne dem",
     "language-menu-buffer-identify-feature": "Vis buffer-alternativer",
     "language-menu-buffer-identify-feature-desc": "Identifiser nærliggende kartobjekter",
     "language-menu-center-map": "Senterer kartet her",
     "language-menu-center-textmap-desc": "Sentrer kartet på det angitte punktet.",
     "language-menu-combine-results": "Kombiner resultater",
     "language-menu-combine-results-desc": "Utfør avanserte operasjoner på flere lister med resultat",
     "language-menu-combine-results-intersect": "Match intersecting results",
     "language-menu-combine-results-intersect-desc": "Vis bare resultatene som er både i den nåværende listen og lagret i en tidligere samling",
     "language-menu-combine-results-subtract": "Fjern (subtraher) lagrede resultater",
     "language-menu-combine-results-subtract-desc": "Fjern et lagret sett av resultatene fra nåværende liste med resultater",
     "language-menu-combine-results-union": "Legg til i resultatlisten",
     "language-menu-combine-results-union-desc": "Kombiner et lagret sett av resultater med nåværende resultatliste",
     "language-menu-default-title": "Alternativer",     
     "language-menu-description": "Hurtigtilgang til vanlige handlinger",
     "language-menu-done": "Ferdig",
	 "language-menu-draw-point": "Tegn et punkt",
     "language-menu-draw-point-desc": "Tegn et punkt på kartet.",
     "language-menu-edit-feature": "Rediger dette objektet",
     "language-menu-edit-feature-description": "Rediger detaljene om dette objektet.",
     "language-menu-enter-offline": "Gå til offlinemodus",
     "language-menu-enter-offline-desc": "Gå til offlinemodus og se cachede kartdata.",
     "language-menu-enter-online": "Gå til onlinemodus",
     "language-menu-enter-online-desc": "Gå til onlinemodus og se levende kartdata fra nettet.",
	 "language-menu-export-results-to-csv": "Eksporter til CSV",
     "language-menu-export-results-to-csv-desc": "Eksporter resultater til CSV",
     "language-menu-export-results-to-shp": "Eksporter til Shapefile",
     "language-menu-export-results-to-shp-desc": "Eksporter resultater til Shapefile",
     "language-menu-export-results-to-xlsx": "Eksporter til XLSX",
     "language-menu-export-results-to-xlsx-desc": "Eksporter resultater til XLSX",
     "language-menu-footer-menu-desc": "Bunnmeny",
     "language-menu-global-open": "Åpne",
     "language-menu-global-open-desc": "Velg et tidligere lagret prosjekt for hente lagrede innstillinger",
     "language-menu-global-save": "Lagre",
     "language-menu-global-save-as": "Lagre som",
     "language-menu-global-save-as-desc": "Lagre viewer-innstillingene i et nytt prosjekt",
     "language-menu-global-save-desc": "Lagre viewer-innstillingene i prosjekt",
     "language-menu-global-search": "Søk",
     "language-menu-global-search-desc": "Søk etter objekter i kartet.",
     "language-menu-home-panel": "Se hovedmenyen",
     "language-menu-home-panel-desc": "Se informasjon om denne applikasjonen.",
     "language-menu-identify": "Finn data i kartet",
	 "language-menu-identify-buffered-feature-set-collection": "Vis buffer-alternativer",
     "language-menu-identify-buffered-feature-set-collection-desc": "Identifiser kartobjekter i nærheten av disse resultatene",
     "language-menu-identify-desc": "Klikk eller tegn et rektangel i kartet for å vise informasjon.",
     "language-menu-identify-freehand": "Vis informasjon med frihåndstegning",
     "language-menu-identify-freehand-desc": "Tegn et område i kartet for å vise informasjon.",
     "language-menu-identify-point": "Vis informasjon med punkt",
     "language-menu-identify-point-desc": "Tegn et punkt i kartet for å vise informasjon derfra.",
     "language-menu-identify-rectangle": "Vis informasjon med rektangel",
     "language-menu-identify-rectangle-desc": "Tegn et rektangel for å se informasjon.",
     "language-menu-latitude-geographics": "Latitude Geographics Group Ltd.",
     "language-menu-latitude-geographics-desc": "Latitude Geographics Group Ltd.",
     "language-menu-list-offline-maps-actions-desc": "Offline Profile Actions",
     "language-menu-list-offline-maps-actions-refresh": "Oppfrisk",
     "language-menu-list-offline-maps-actions-refresh-desc": "Oppfrisk listen over kart som er tilgjengelig offline.",
	 "language-menu-map-context-menu-title": "Punktalternativer",
     "language-menu-map-context-menu-title-desc": "Alternativer relatert til et gitt punkt på kartet.",     
     "language-menu-map-layers": "Slå karlag av eller på",
     "language-menu-map-layers-desc": "Slå kartlag av eller på, endre innstillinger og se tegnforklaring.",
	 "language-menu-map-layers-expand": "Ekspaneder og kollaps {0} kartlagsgruppen",
     "language-menu-maptip-actions": "Handlinger",
     "language-menu-maptip-actions-desc": "Karttipshandlinger",
     "language-menu-maptip-actions-view-details": "Se mer informasjon",
     "language-menu-maptip-actions-view-details-desc": "Se ytterligere informasjon om dette objektet",
     "language-menu-menus-description": "Jeg vil...-menyer",
     "language-menu-no-items": "Ingen objekter!",
	 "language-menu-offline-map-editor-geometry-actions-circle": "Sirkel",
     "language-menu-offline-map-editor-geometry-actions-circle-desc": "Tegn en sirkel rundt ønsket geometri..",
     "language-menu-offline-map-editor-geometry-actions-clear": "Visk ut",
     "language-menu-offline-map-editor-geometry-actions-clear-desc": "Visk ut området med geometrien.",
     "language-menu-offline-map-editor-geometry-actions-currentextent": "Synlig kartutsnitt",
     "language-menu-offline-map-editor-geometry-actions-currentextent-desc": "Bruk det synlige kartutsnittet for å legge inn geometri.",
     "language-menu-offline-map-editor-geometry-actions-desc": "Geometrihandlinger",
     "language-menu-offline-map-editor-geometry-actions-ellipse": "Ellipse",
     "language-menu-offline-map-editor-geometry-actions-ellipse-desc": "Tegn en ellipse med geometrien.",
     "language-menu-offline-map-editor-geometry-actions-freehandpolygon": "Frihåndspolygon",
     "language-menu-offline-map-editor-geometry-actions-freehandpolygon-desc": "Tegn et frihåndspolygon over området for geometri.",
     "language-menu-offline-map-editor-geometry-actions-polygon": "Polygon",
     "language-menu-offline-map-editor-geometry-actions-polygon-desc": "Tegn et polygon rundt geometri.",
     "language-menu-offline-map-editor-geometry-actions-rectangle": "Rektangel",
     "language-menu-offline-map-editor-geometry-actions-rectangle-desc": "Tegn et rektangel rund ønsket geometri.",
     "language-menu-plot-coordinate": "Plott en koordinat",
     "language-menu-plot-coordinate-desc": "Plott en koordinat på kartet.",
     "language-menu-powered-by-geocortex": "Powered by Geocortex",
     "language-menu-powered-by-geocortex-desc": "Powered by Geocortex",
     "language-menu-project-actions-desc": "Se alternativer for prosjektet.",
     "language-menu-projects-actions-desc": "Prosjektalternativer Actions",
     "language-menu-projects-actions-refresh-desc": "Oppdater listen med prosjekter.",
     "language-menu-remove-user-added-layer": "Fjern kartlag",
     "language-menu-remove-user-added-layer-desc": "Fjern det bruker-valgte kartlaget.",
     "language-menu-results-add-feature": "Legg til i resltater",
     "language-menu-results-add-feature-desc": "legg dette kartobjektet til nåværende resultatsett",
     "language-menu-results-list-actions-desc": "Handlinger for resultatliste",
     "language-menu-results-remove-feature": "Fjern fra resultat",
     "language-menu-results-remove-feature-desc": "Fjern dette kartobjektet fra nåværende resultatsett",
     "language-menu-results-table-actions-desc": "Handlinger for resultattabell",
	 "language-menu-run-a-workflow": "Utfør en handling",
     "language-menu-run-report": "Kjør en rapport",
     "language-menu-run-report-desc": "Kjør en rapport på valgte resultater",
     "language-menu-run-workflow": "Utfør en handling",
     "language-menu-run-workflow-desc": "Velg fra en liste med mulige handlinger.",
	 "language-menu-save-results": "Lagre resultater",
     "language-menu-save-results-desc": "Lagre listen med resultater for senere bruk",
	 "language-menu-settings-description": "Alternativer for mobil",
	 "language-menu-show-charting-view": "Diagramvisning",
     "language-menu-show-charting-view-desc": "Skift til diagramvisning",
     "language-menu-show-log": "Vis logg",
     "language-menu-show-log-desc": "Vis viewerens logg, inkludert diagnostiske feil og versjonsnummer.",
     "language-menu-show-results-list": "Listevisning",
     "language-menu-show-results-list-desc": "Skift til listevisning",
     "language-menu-show-results-table": "Tabellvisning",
     "language-menu-show-results-table-desc": "Skift til tabellvisning",
	 "language-menu-social-links-menu-desc": "Linker til sosiale medier",
	 "language-menu-switch-to-layerlist": "Vis kartlagsliste",
     "language-menu-switch-to-layerlist-desc": "Vis listen med tilgjengelige kartlag",
     "language-menu-switch-to-legend": "Vis tegnforklaring",
     "language-menu-switch-to-legend-desc": "Vis tegnforklaring for synlige kartlag",
     "language-menu-title": "Jeg vil...",
     "language-menu-visualization": "Slå på/av kartlagsvisualisering",
     "language-menu-visualization-desc": "Bruk varme- eller klumpekart.",
     "language-menu-zoom": "Zoom til objekt",
     "language-menu-zoom-description": "Zoom til dette objektet i kartet.",
     "language-menu-zoom-in": "Zoom inn",
     "language-menu-zoom-initial-extent": "Gå tilbake til det første kartutsnittet",
     "language-menu-zoom-initial-extent-desc": "Gå tilbake til det første kartutsnittet og målestokknivået.",
     "language-menu-zoom-out": "Zoom ut",
     "language-menu-zoom-to-layer": "Zoom til full målestokk",
     "language-menu-zoom-to-layer-desc": "Zoom kartet til lagets fulle utstrekning.",
     "language-menu-zoom-to-visible-scale": "Zoom til synlig målestokk",
     "language-menu-zoom-to-visible-scale-desc": "Zoomer kartet til en målestokk hvor laget er synlig.",
     "language-months-0": "Januar",
     "language-months-1": "Februar",
     "language-months-10": "November",
     "language-months-11": "Desember",
     "language-months-2": "Mars",
     "language-months-3": "April",
     "language-months-4": "Mai",
     "language-months-5": "Juni",
     "language-months-6": "Juli",
     "language-months-7": "August",
     "language-months-8": "September",
     "language-months-9": "Oktober",
	 "language-offline-errors-bundlenotfound": "Bunt ble ikke funnet.",
     "language-offline-errors-bundleoffiline": "Det er ikke mulig å lage en bunt offline.",
     "language-offline-errors-canceled": "Avbrutt.",
     "language-offline-errors-cancelrejected": "Kan ikke avbryte akkurat nå.",
     "language-offline-errors-isactive": "Kan ikke fjerne det aktive offlike-kartet.",
     "language-offline-errors-loadfailed": "Kunne ikke laste.",
     "language-offline-errors-notfound": "Offline-profilen ble ikke funnet.",
     "language-offline-errors-notnativeinitialized": "Denne operasjonen kan kun bli utført på mobilklienten.",
     "language-offline-errors-savefailed": "Kunne ikke lagre.",
     "language-offline-progress-basemapdownload-canceled": "{0} avbrutt.",
     "language-offline-progress-basemapdownload-completed": "{0} lastet ned.",
     "language-offline-progress-basemapdownload-connecting": "{0} kobler til...",
     "language-offline-progress-basemapdownload-downloading": "{0} {1}% lastet ned...",
     "language-offline-progress-basemapdownload-failed": "Bakgrunnskartet '{0}' feilet under nedlasting: {1}",
     "language-offline-progress-basemapexport-canceled": "{0} avbrutt.",
     "language-offline-progress-basemapexport-completed": "{0} generert og nedlastet.",
     "language-offline-progress-basemapexport-connecting": "{0} kobler til for å generere...",
     "language-offline-progress-basemapexport-downloading": "{0} {1}% lastet ned...",
     "language-offline-progress-basemapexport-failed": "{0} feilet. {1}",
     "language-offline-progress-basemapexport-processing": "{0} genererer...",
     "language-offline-progress-complete": "Fullført.",
     "language-offline-progress-downloadingsite": "Laster ned sideressurser.",
     "language-offline-progress-removingofflinemap": "Fjerner offlinekart.",
     "language-offline-progress-savingofflinemap": "Lagrer offlinekart.",
     "language-offline-progress-starting-basemap-download": "Starter nedlasting av bakgrunnskart.",
     "language-offline-progress-starting-sync": "Starter synkronisering av featurelager.",
     "language-offline-progress-unregisteringreplica": "Uregistrert replika.",
     "language-page-displaying": "Viser",	 
     "language-page-first": "Første",
     "language-page-last": "Siste",
     "language-page-next": "Neste",
	 "language-page-of": "av",
     "language-page-page": "Side",
     "language-page-prev": "Forrige",
	 "language-page-total": "Total",
     "language-project-error-delete": "Prosjektet kunne ikke slettes. Se i loggfilen for flere detaljer.",
     "language-project-error-delete-denied": "Du har ikke rettigheter for å slette dette prosjektet.",
     "language-project-error-owner": "Du eier ikke dette prosjektet.",
     "language-project-error-read": "Prosjektet kunne ikke åpnes. Se i loggfilen for flere detaljer.",
     "language-project-error-read-denied": "Du har ikke rettigheter til å åpne dette prosjektet.",
     "language-project-error-read-not-found": "Kunne ikke finne prosjektet med  ID \"{0}\".",
     "language-project-error-sign-in-required": "Dette prosjektet krever at du logger inn. Logg inn for å åpne prosjektet.",
     "language-project-error-title": "Prosjektfeil",
     "language-project-error-write": "Prosjektet kunne ikke lagres. Se i loggfilen for flere detaljer.",
     "language-project-error-write-denied": "Du har ikke rettigher til å lagre dette prosjektet.",
     "language-project-sign-in": "Logg inn",
     "language-results": "Resultater",
     "language-results-displaying": "Viser",
	 "language-results-export-to-alert-error-message": "Feil ved eksportering til \".{0}\"",
     "language-results-export-to-confirm-content": "Filen \".{0}\" er klar for å lastes ned. Vil du fortsette?",
     "language-results-export-to-confirm-title": "Nedlasting av \".{0}\" ",
     "language-results-export-to-status-message": "Eksporterer til \".{0}\"",
     "language-results-menu-description": "Objekthandlinger for resultatlisten",
     "language-results-page": "Side",
	 "language-results-page-first": "Første side",
     "language-results-page-last": "Siste side",
	 "language-results-page-next": "Neste side",
     "language-results-page-of": "av",
	 "language-results-page-prev": "Forrige side",
     "language-results-sort": "Sorter resultater",
     "language-results-toggle-list-view": "Bytt til liste",
	 "language-results-toggle-list-view-desc": "Se resultatene i listeformat",
     "language-results-toggle-table-view": "Bytt til tabell",
	 "language-results-toggle-table-view-desc": "Se resultatene i tabellformat"
     "language-results-total": "Totalt",
     "language-search-fsc-display-name": "Søkeresultater: {0}",
     "language-search-world-place-names": "Stedsnavn i verden",
	 "language-smart-panel-back": "Gå tilbake i panelet",
     "language-smart-panel-close": "Lukk fane",
     "language-smart-panel-maximize-restore": "Maksimer/gjenopprett panelet",
     "language-smart-panel-menu": "Handlingsmeny for panel. Klikk for å åpne/lukke.",
     "language-smart-panel-resize": "Dra for å endre størrelsen på panelet",
     "language-states-buffering-description": "Buffering er valgt for aktivt verktøy.",
     "language-states-default-description": "Vieweren har ikke noe aktivt.",
     "language-states-draw-markup-state-description": "Tegningsverktøyet er aktivt.",
     "language-states-edit-state-description": "Verktøyet for å velge et objekt for redigering er aktivt.",
     "language-states-editing-active-state-description": "Redigeringsmodul er aktiv.",
     "language-states-editing-state-description": "En tegning blir redigert akkurat nå.",
     "language-states-feature-editing-state-description": "Verktøyet for oppretting av kartobjekt er aktivt.",
     "language-states-feature-editing-state-graphic-description": "Verktøyet for oppretting av kartobjekt arbeider med en grafikk.",
     "language-states-feature-editing-state-point-graphic-description": "Verktøyet for oppretting av kartobjekter redigerer en punktbasert grafikk.",
     "language-states-identify-state-description": "Identifiseringsverktøyet er aktivt.",
     "language-states-measure-state-description": "Måleverktøyet er aktivt.",
     "language-states-plotcoordinates-state-description": "Verktøyet for plotting av koordinater er aktivt.",
     "language-states-snapping-description": "Hekting (snapping) er påslått for det aktive verktøyet.",
     "language-states-transient-active-description": "Minst en verktøylinje er åpen.",  
     "language-tab-scroll-next": "Neste lag",
     "language-tab-scroll-prev": "Forrige lag",
	 "language-toolbar-3rd-party-maps-show-maps": "Linked Maps",
     "language-toolbar-3rd-party-maps-show-maps-tooltip": "Display linked maps in the external component view",
     "language-toolbar-analysis-location-info": "Stedsinformasjon",
     "language-toolbar-analysis-location-information": "Stedsinformasjon",
     "language-toolbar-analysis-measurement-tools": "Måleverktøy",
	 "language-toolbar-arcgis-export-web-map": "Lagre til ArcGIS",
     "language-toolbar-arcgis-export-web-map-tooltip": "Lagre eksisterende kart ArcGIS",
     "language-toolbar-arcgis-view-my-content": "Se mitt innhold",
     "language-toolbar-arcgis-view-my-content-tooltip": "Se mitt innhold i ArcGIS",
     "language-toolbar-bookmark": "Bokmerker",
     "language-toolbar-bookmark-open": "Åpne bokmerkevisning",
	 "language-toolbar-buffer-toggle-tooltip": "Lag et bufferområde rundt seleksjonen",
     "language-toolbar-buffering-alt-disable": "Slå av buffering for aktivt verktøy",
     "language-toolbar-buffering-alt-enable": "Slå på buffering for aktivt verktøy",
     "language-toolbar-buffering-disable": "Slå av buffering",
     "language-toolbar-buffering-enable": "Slå på buffering",
	 "language-toolbar-charting-show-charts": "Se grafer",
     "language-toolbar-charting-show-charts-tooltip": "Åpne grafvisning",
     "language-toolbar-clear-all": "Fjern alt",
	 "language-toolbar-editing-create-new-feature": "Opprett nytt kartobjekt",
     "language-toolbar-editing-create-new-feature-geolocation": "Bruk posisjon",
     "language-toolbar-editing-create-new-feature": "Lag nytt objekt",
     "language-toolbar-editing-create-new-feature-tooltip": "Lag et nytt objekt i kartet",
     "language-toolbar-editing-data": "Data",
     "language-toolbar-editing-edit": "Rediger",
     "language-toolbar-editing-manage-offline-data": "Behandle offlinedata",
     "language-toolbar-editing-manage-offline-data-tooltip": "Velg, synkroniser, og tøm offlinedata",
     "language-toolbar-editing-tools": "Rediger objekter",
     "language-toolbar-erase": "Fjern",
     "language-toolbar-find-data": "Finn data",
	 "language-toolbar-find-data-tools": "Verktøy for å finne data",
	 "language-toolbar-group-3rd-party-maps": "Linked Maps",
	 "language-toolbar-group-advanced-measurement": "Avansert måling",
     "language-toolbar-group-analysis": "Analyse",
	 "language-toolbar-group-arcgis": "ArcGIS",
     "language-toolbar-group-draw": "Tegne",
     "language-toolbar-group-edit": "Rediger",
     "language-toolbar-group-edit-features": "Rediger objekter",
     "language-toolbar-group-editing": "Rediger",
     "language-toolbar-group-find-data": "Finn data",
	 "language-toolbar-group-find-data-tools": "Finn",
     "language-toolbar-group-global-tasks": "Globale oppgaver",
     "language-toolbar-group-home": "Standardverktøy",
	 "language-toolbar-group-layers": "Kartlag",
     "language-toolbar-group-measurement": "Måling",
	 "language-toolbar-group-measurement-tools": "Måleverktøy",
	 "language-toolbar-group-native": "Native",
     "language-toolbar-group-navigation": "Navigering",
     "language-toolbar-group-offline-management": "Behandle offlinedata",
	 "language-toolbar-group-plotcoordinates": "Koordinater",
     "language-toolbar-group-tasks": "Oppgaver",
     "language-toolbar-group-tools": "Verktøy",
     "language-toolbar-home-sub": "Hjelp",
     "language-toolbar-home-tooltip": "Går til hjelpeteksten",
     "language-toolbar-identify-freehand": "Frihånd",
     "language-toolbar-identify-freehand-desc": "Klikk og hold nede, tegn deretter en linje på frihånd for å vise informasjon.",
     "language-toolbar-identify-freehand-polygon": "Frihåndsområde",
     "language-toolbar-identify-freehand-polygon-desc": "Tegn et område på frihånd i kartet for å vise informasjon",
     "language-toolbar-identify-freehand-polygon-tooltip": "Vis informasjon fra kartet ved å tegne et område på frihånd",
     "language-toolbar-identify-freehand-tooltip": "Finn informasjon fra kartet ved å tegne et område på frihånd",
	 "language-toolbar-identify-layers-change": "Identifiserbare kartlag",
     "language-toolbar-identify-layers-change-tooltip": "Slå på/av kartlag som skal brukes i identifiseringsoperasjoner",
     "language-toolbar-identify-point": "Punkt",
     "language-toolbar-identify-point-desc": "Klikk et sted i kartet for å vise informasjon.",
	 "language-toolbar-identify-point-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å se hva som finnes der.",
     "language-toolbar-identify-point-tooltip": "Finn informasjon fra kartet",
     "language-toolbar-identify-polygon": "Område",
     "language-toolbar-identify-polygon-desc": "For å finne informasjon, tegn et område på kartet. Dobbeltklikk for å avslutte.",
	 "language-toolbar-identify-polygon-desc-keyboard": "For å finne informasjon, bruk piltastene for å flytte punktet. Trykk ENTER for å plassere punktet og starte plassering av neste punkt. Trykk to ganger på ENTER tfor å avslutte.",
     "language-toolbar-identify-polygon-tooltip": "Finn informasjon fra kartet ved å tegne et område",
     "language-toolbar-identify-polyline": "Linje",
     "language-toolbar-identify-polyline-desc": "For å finne informasjon, klikk og dra for å tegne en linje i kartet. Dobbeltklikk for å avslutte.",
	 "language-toolbar-identify-polyline-desc-keyboard": "For å finne informasjon, bruk piltastene for å flytte punktet. Trykk ENTER for å plassere punktet og starte plassering av neste punkt. Trykk to ganger på ENTER tfor å avslutte.",
     "language-toolbar-identify-polyline-tooltip": "Finn informasjon fra kartet ved å tegne en linje",
     "language-toolbar-identify-rectangle": "Rektangel",
     "language-toolbar-identify-rectangle-desc": "For å finne informasjon, klikk og dra for å tegne et rektangel i kartet.",
     "language-toolbar-identify-rectangle-tooltip": "Finn informasjon fra kartet ved å tegne et rektangel",
	 "language-toolbar-identify-snapping-tooltip": "Slå på/av hekting (snapping) under identifisering",
     "language-toolbar-information-actions": "Informasjon og handlinger",
	 "language-toolbar-markup-change-markup-style": "Stiler",
     "language-toolbar-markup-circle": "Sirkel",
     "language-toolbar-markup-circle-desc": "Dra en sirkel inn i kartet",
     "language-toolbar-markup-circle-tooltip": "Tegn en sirkel i kartet",
     "language-toolbar-markup-clear": "Fjern målinger",
     "language-toolbar-markup-clear-tooltip": "Fjern alle tegninger fra kartet",
	 "language-toolbar-markup-delete": "Fjern",
     "language-toolbar-markup-delete-desc": "Klikk for å midlertidig eller permanent slette en tegning. Denne funksjonen kan ikke angres.",
     "language-toolbar-markup-delete-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å midlertidig eller permanent slette en tegning. Denne funksjonen kan ikke angres.",
     "language-toolbar-markup-delete-tooltip": "Slett en eksisterende tegning",
     "language-toolbar-markup-drawing": "Opprett",
     "language-toolbar-markup-drawing-edit-tools": "Rediger",
     "language-toolbar-markup-drawing-tools": "Tegn",
	 "language-toolbar-markup-edit": "Rediger",
     "language-toolbar-markup-edit-desc": "Klikk på en eksisterende tegning for å starte redigering av tegningen.",
     "language-toolbar-markup-edit-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å begynne redigering av tegningen.",
     "language-toolbar-markup-edit-desc-shortcuts": "Bruk piltastene for å flytte, R for å rotere, S for å skalere, V for å velge knekkpunkt. Kombiner med ALT for mer nøyaktig kontroll. Kombiner med SHIFT for å angre.",
     "language-toolbar-markup-edit-desc-shortcuts-zoom": "Bruk piltastene for å flytte, S for å skalere.  Kombiner med ALT for mer nøyaktig kontroll. Kombiner med SHIFT for å angre..",
     "language-toolbar-markup-edit-tooltip": "Rediger en eksisterende tegning",
     "language-toolbar-markup-edit-zoomin-tool": "ZoomInTool",
     "language-toolbar-markup-edit-zoomout-tool": "ZoomOutTool",
     "language-toolbar-markup-ellipse": "Ellipse",
     "language-toolbar-markup-ellipse-desc": "Klikk og dra for å tegne en ellipse i kartet.",
     "language-toolbar-markup-ellipse-tooltip": "Tegn en ellipse i kartet",
	      "language-toolbar-markup-export": "Eksporter tegninger",
     "language-toolbar-markup-export-tooltip": "Eksporter tegninger til shapefile",
     "language-toolbar-markup-freehand": "Frihånd",
     "language-toolbar-markup-freehand-desc": "Hold musknappen (eller fingertuppen din) nede, og tegn en linje med frihånd.",
     "language-toolbar-markup-freehand-polygon": "Frihånd område",
     "language-toolbar-markup-freehand-polygon-desc": "Hold musknappen (eller fingertuppen din) nede, og tegn et område med frihånd.",
     "language-toolbar-markup-freehand-polygon-tooltip": "Tegn et frihåndsområde på kartet",
     "language-toolbar-markup-freehand-tooltip": "Tegn en linje på frihånd i kartet",
	 "language-toolbar-markup-palette-small-change-style": "Stiler",
     "language-toolbar-markup-palette-small-clear-all": "Fjern alt",
     "language-toolbar-markup-palette-small-delete": "Slett",
     "language-toolbar-markup-palette-small-edit": "Rediger",
     "language-toolbar-markup-point": "Punkt",
     "language-toolbar-markup-point-desc": "Klikk i kartet for å legge til et punkt.",
	 "language-toolbar-markup-point-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å legge det til kartet.",
     "language-toolbar-markup-point-tooltip": "Legg til et punkt i kartet",
     "language-toolbar-markup-polygon": "Område",
     "language-toolbar-markup-polygon-desc": "Klikk i kartet for å tegne et område. Dobbeltklikk for å avslutte.",
	 "language-toolbar-markup-polygon-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å plassere punktet og starte plassering av neste punkt. Trykk to ganger på ENTER for å fullføre.",
     "language-toolbar-markup-polygon-tooltip": "Tegn et område med form som du bestemmer i kartet",	 
     "language-toolbar-markup-polyline": "Linje",
     "language-toolbar-markup-polyline-desc": "Klikk i kartet for å tegne en linje. Dobbeltklikk for å avslutte.",
	 "language-toolbar-markup-polyline-desc-keyboard": "Bruk piltastene for å flytte punktet. Trykk ENTER for å plassere punktet og starte plassering av neste punkt. Trykk to ganger på ENTER for å fullføre.",
     "language-toolbar-markup-polyline-tooltip": "Tegn en linje i kartet",
     "language-toolbar-markup-rectangle": "Rektangel",
     "language-toolbar-markup-rectangle-desc": "Klikk og dra for å tegne et rektangel i kartet.",
     "language-toolbar-markup-rectangle-tooltip": "Tegn et rektangel i kartet",
	 "language-toolbar-markup-text": "Tekst",
     "language-toolbar-markup-text-desc": "Trykk på stedet du vil legge til tekst på kartet.",
     "language-toolbar-markup-text-tooltip": "Legg til din egen tekst på kartet",
     "language-toolbar-menu-global-open": "Åpne",
     "language-toolbar-menu-global-open-desc": "Velg et tidligere lagret prosjekt for å gjenopprette lagre tilstand",
     "language-toolbar-menu-global-save": "Lagre",
     "language-toolbar-menu-global-save-as": "Lagre som",
     "language-toolbar-menu-global-save-as-desc": "Lagre tilstanden til vieweren i et nytt prosjekt",
     "language-toolbar-menu-global-save-desc": "Lagre tilstanden til vieweren i et prosjekt",
     "language-toolbar-menu-global-save-save-as": "Lagre/Lagre som",
     "language-toolbar-multitool": "Multi-verktøy",
     "language-toolbar-native-showofflinemaps": "Tilgjengelige kart uten nettilgang (Offlinekart)",
     "language-toolbar-native-showofflinemaps-tooltip": "Åpne listen med offline kart",
     "language-toolbar-navigation": "Navigering",
     "language-toolbar-navigation-full-extent": "Full utstrekning",
     "language-toolbar-navigation-full-extent-tooltip": "Gå tilbake til full kartustrekning",
     "language-toolbar-navigation-home": "Hjelp",
     "language-toolbar-navigation-home-sub": "Hjelp",
     "language-toolbar-navigation-home-tooltip": "Går til hjelpeteksten",
     "language-toolbar-navigation-initial-extent": "Hele kartutstrekningen",
     "language-toolbar-navigation-initial-extent-tooltip": "Gå tilbake til kartets opprinnelige utstrekning",
     "language-toolbar-navigation-next-extent": "Neste utstrekning",
     "language-toolbar-navigation-next-extent-tooltip": "Zoom til neste utstrekning",
     "language-toolbar-navigation-pan": "Panorer",
     "language-toolbar-navigation-pan-tooltip": "Avbryter hvis du har aktive verktøy, og setter kartet i panoreringsmodus",
     "language-toolbar-navigation-previous-extent": "Forrige utstrekning",
     "language-toolbar-navigation-previous-extent-tooltip": "Zoom til forrige utstrekning",
     "language-toolbar-navigation-zoom-in": "Zoom inn",
     "language-toolbar-navigation-zoom-in-desc": "Klikk og dra i kartet for å velge et område. Kartet zoomer til det området.",
     "language-toolbar-navigation-zoom-in-tooltip": "Tegn et område i kartet for å zoome dit",
     "language-toolbar-navigation-zoom-out": "Zoom ut",
     "language-toolbar-navigation-zoom-out-desc": "Tegn et rektangel i kartet for å zoome ut, samtidig som det området forblir sentrert",
     "language-toolbar-navigation-zoom-out-tooltip": "Tegn et område i kartet og zoom ut, mens området forblir sentrert",
     "language-toolbar-not-available": "Verktøylinjen er ikke tilgjengelig",
	 "language-toolbar-open-toolbar": "Åpne verktøylinje",
     "language-toolbar-select-layers-toggle-off-name": "Lagene er filtrert",
     "language-toolbar-select-layers-toggle-on-name": "Filtrer lag",
     "language-toolbar-select-layers-toggle-tooltip": "Filtrer lag for identifisering",
     "language-toolbar-show-layerlist": "Kartlagsliste",
     "language-toolbar-show-layerlist-desc": "Vis listen over tilgjengelige kartlag",
     "language-toolbar-snapping-alt-disable": "Slå av hekting (snapping) for det aktive verktøyet",
     "language-toolbar-snapping-alt-enable": "Slå på henktig (snapping) for det aktive verktøyet",
     "language-toolbar-snapping-disable": "Slå av hekting (snapping)",
     "language-toolbar-snapping-enable": "Slå på hekting (snapping)",
     "language-toolbar-snapping-select-layers": "Velg lag som skal kunne hektes ",
     "language-toolbar-snapping-select-layers-tooltip": "Endre hvilke lag som skal kunne hektes",
     "language-toolbar-tab-analysis": "Analyse",
     "language-toolbar-tab-editing": "Redigering",
	 "language-toolbar-tab-file": "Fil",
     "language-toolbar-tab-home": "Hjem",
     "language-toolbar-tab-map": "Kart",
     "language-toolbar-tab-navigation": "Navigering",
     "language-toolbar-tab-offline": "Offline",
     "language-toolbar-tab-tasks": "Oppgaver",
	 "language-toolbar-tab-tools": "Verktøy",
     "language-toolbar-tasks-export-map": "Eksporter",
     "language-toolbar-tasks-export-map-tooltip": "Lagre kartbilde",
     "language-toolbar-tasks-identify": "Vis data",
     "language-toolbar-tasks-identify-tooltip": "Finn data i kartet",
     "language-toolbar-tasks-print-map": "Utskrift",
     "language-toolbar-tasks-print-map-tooltip": "Lag en fil av dette kartet som du kan skrive ut",
     "language-toolbar-tasks-printing": "Skriver ut",
	 "language-toolbar-tasks-share": "Del",
     "language-toolbar-tasks-share-tooltip": "Del nåværende kart på de vanligste sosiale medier",
     "language-toolbar-tasks-upload-data": "Last opp data",
     "language-toolbar-tasks-upload-data-tooltip": "Last opp kartlag fra pc-en din for å se de i kartet",
     "language-toolbar-title": "Verktøylinje",
	 "language-toolbar-toggle-buffer-off-name": "Buffering på",
     "language-toolbar-toggle-buffer-on-name": "Buffer alternativer",
     "language-toolbar-toolbar": "Verktøylinje",
	 "language-ui-table-sorted-ascending": "Kolonneoverskrift. {0} - Stigende sortert.",
     "language-ui-table-sorted-descending": "Kolonneoverskrift. {0} - Synkende sortert.",
     "language-ui-table-unsorted": "Kolonneoverskrift. {0} - Usortert",
     "language-webmap-field-name-visible": "Synlig",
     "language-webmap-layer-name-point": "Punkter",
     "language-webmap-layer-name-polygon": "Polygoner",
     "language-webmap-layer-name-polyline": "Linjer"
}